# POST http://localhost:8000/api/equipment_exception/update HTTP/1.1
# Content-Type: application/json

# {
#   "excep_id": "20191009-195557-3525699",
#   "eqp_id": null,
#   "excep_type": "testEdit",
#   "excep_code": null,
#   "excep_comment": "testEdit",
#   "excep_time": null,
#   "excep_location": "testEdit",
#   "excep_process_user": null,
#   "excep_process_time": null,
#   "excep_process_result": "testEdit",
#   "excep_process_remark": "testEdit",
#   "excep_recovery_flag": "testEdit",
#   "excep_recovery_time": null,
#   "excep_recovery_cost": 0,
#   "excep_state": "testEdit",
#   "excep_out_user": null,
#   "excep_out_time": null,
#   "excep_out_vendor": "testEdit",
#   "excep_out_comment": "testEdit",
#   "excep_create_user": "[1]1"
# }

# GET http://localhost:8000/api/equipment_exception/list?excep_id=20191009-195557-3525699 HTTP/1.1

DELETE http://localhost:8000/api/equipment_exception/del?excep_id=20191009-195557-3525699 HTTP/1.1